openapi: "3.0.0"

info:
  title: "Chat app"
  description: "A simple chat app"
  version: "1.0"

paths:
  /ping:
    get:
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
